<?php

return array(
    'config' => '系统配置',
    'ecmall_integrate_guide' => 'ECMall 整合向导',
    'welcome_integrate_ecmall' => '您好，欢迎使用 ECMall 整合程序',
    'have_missing_item' => '您忘了填写以下项目',
    'ucenter_info' => '请填写 UCenter 的相关信息',
    'uc_connect' => 'UCenter 连接方式',
    'uc_api' => 'UCenter 的 URL',
    'uc_ip' => 'UCenter 的 IP',
    'uc_password' => 'UCenter 创始人密码',
    'app_name' => 'ECMall 网站名称',
    'app_url' => 'ECMall 访问地址',
    'uc_api_error' => 'UCenter 的 URL 输入有误，必须以 http:// 开头',
    'app_url_error' => 'ECMall 访问地址输入有误，必须以 http:// 开头',
    'dns_error' => 'UCenter URL域名解析失败，请手动设置UCenter的IP',
    'get_ucinfo_failed' => '获取用户中心信息数据失败，请返回检查',
    'charset_error' => 'ECMall 字符集（%s）和 UCenter 字符集（%s）不同，请选择正确的版本重新安装 ECMall 或 UCenter',
    'version_error' => '您的 UCenter 服务端版本（%s）与客户端版本（%s）不一致，请下载正确的客户端版本重新整合',
    'app_exists' => 'UCenter 只能整合一个 ECMall，如果需要重新整合，请您登录 UCenter 管理中心应用管理将 ECMall 应用删除后再进行整合',
    'password_error' => 'UCenter 创始人密码错误，请重新填写',
    'connect_error' => 'UCenter 通信失败，请检查 UCenter URL地址是否能正常访问',
    'uc_db_error' => 'UCenter数据库连接失败，您可以尝试选择Http方式连接',
    'finish' => '完成',
    'integrate_successed'          => '恭喜您！整合UCenter成功！感谢您使用ECMall，请在下面选择您的去向',
    'config_title'          => 'UCenter整合程序',
    'config_desc'          => '支持 ucenter1.0 和 1.5 版本',
    'finish_title'          => 'UCenter整合完成',
    'finish_desc'          => '',
    'close_window' => '关闭',
    'frontend' => '商城首页',
    'backend' => '商城后台',
    'install_first'  => '请先安装ECMall',
    'password_inconsistent'  => '两次输入的密码不一致',
    'email_error'  => 'EMail格式错误',
    'apptagtemplates'  => array(
        'goods_name'   =>    '商品名称',
        'uid'  => '用户ID',
        'username'  => '用户名',
        'dateline'  => '日期',
        'url'  => 'URL地址',
        'image'  => '图片',
        'goods_price'  => '商品价格',
    ),
    'user_not_exists'  => '用户不存在，请检查您的输入，您可以尝试使用新的用户',
    'admin_password_error'  => '您输入的用户密码有误，请检查',
    'unknow_error'  => '未知错误',
    'invalid_user_name'  => '不合法的用户名',
    'blocked_usre_name'  => '该用户名包含不允许注册的词语，无法使用',
    'user_exists'  => '用户已存在，请更换一个',
    'blocked_email'  => '该EMail已被禁止注册，请更换',
    'email_exists'  => '该EMail已被注册',
    'exists_user'  => '使用 ucenter 现有的用户',
    'new_user'  => '使用新用户',
    'user_name'  => '管理员用户名',
    'email'  => '管理员EMail',
    'password'  => '管理员密码',
    'password_confirm'  => '密码确认',
    'mall_admin_info'   => '请填写整合后 ECMall 的管理员信息',
    'mall_admin_info_desc' => '',
    'integrate_locked' => '整合程序已锁定，如果您想重新运行整合程序，请删除 data/integrate.lock 文件。',
    'uc_client_not_exist' => 'uc_client 目录不存在或文件不完整，请检查后再运行整合程序。',
    'attension' => '请注意',
    'attension_content' => '整合后，ECMall 中现有的用户、店铺及相关信息都将被删除，请确认后再往下执行。',
    'please_read_warning' => '请确认您是否已经知道整合后将引起的后果，若您是初装用户，可以忽略',
);

?>
