web4:
  build: .
  volumes:
    - ./upload/:/var/www/html/
  links:
    - mysql
mysql:
  image: mysql
  expose:
    - 3306
  volumes:
    - ./data/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123456
